### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by shofizone** [anandnet/flutter_video_info#15]
This error show in the console whenever I try to get info for an **Flv** video.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
W/System.err(32293): 	at java.text.SimpleDateFormat.parseInternal(SimpleDateFormat.java:1540)
W/System.err(32293): 	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1528)
W/System.err(32293): 	at java.text.DateFormat.parse(DateFormat.java:360)
W/System.err(32293): 	at com.example.flutter_video_info.FlutterVideoInfoPlugin.getVidInfo(FlutterVideoInfoPlugin.java:72)
W/System.err(32293): 	at com.example.flutter_video_info.FlutterVideoInfoPlugin.onMethodCall(FlutterVideoInfoPlugin.java:49)
W/System.err(32293): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err(32293): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(32293): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
W/System.err(32293): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(32293): 	at android.os.MessageQueue.next(MessageQueue.java:331)
W/System.err(32293): 	at android.os.Looper.loop(Looper.java:149)
W/System.err(32293): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
W/System.err(32293): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(32293): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/System.err(32293): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Comment by chaudharydeepanshu** [comment]
Got the same issue today:

```
[   +9 ms] W/System.err(32494): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
[        ] W/System.err(32494): 	at java.text.SimpleDateFormat.parseInternal(SimpleDateFormat.java:1772)
[        ] W/System.err(32494): 	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1759)
[        ] W/System.err(32494): 	at java.text.DateFormat.parse(DateFormat.java:391)
[        ] W/System.err(32494): 	at com.example.flutter_video_info.FlutterVideoInfoPlugin.getVidInfo(FlutterVideoInfoPlugin.java:77)
[        ] W/System.err(32494): 	at com.example.flutter_video_info.FlutterVideoInfoPlugin.onMethodCall(FlutterVideoInfoPlugin.java:49)
[        ] W/System.err(32494): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
[        ] W/System.err(32494): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
[        ] W/System.err(32494): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] W/System.err(32494): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] W/System.err(32494): 	at android.os.Handler.handleCallback(Handler.java:959)
[        ] W/System.err(32494): 	at android.os.Handler.dispatchMessage(Handler.java:100)
[        ] W/System.err(32494): 	at android.os.Looper.loopOnce(Looper.java:232)
[        ] W/System.err(32494): 	at android.os.Looper.loop(Looper.java:317)
[        ] W/System.err(32494): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
[        ] W/System.err(32494): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] W/System.err(32494): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
[        ] W/System.err(32494): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```
