### ISSUE TITLE
Unparseable date crash on Samsung J7

### ISSUE THREAD

**Issue by qbait** [anandnet/flutter_video_info#7]
I'm getting crash on Samsung J7

```
W/System.err(21861): java.text.ParseException: Unparseable date: "2020 11 17" (at offset 7)
W/System.err(21861): 	at java.text.DateFormat.parse(DateFormat.java:579)
W/System.err(21861): 	at com.example.flutter_video_info.FlutterVideoInfoPlugin.getVidInfo(FlutterVideoInfoPlugin.java:69)
W/System.err(21861): 	at com.example.flutter_video_info.FlutterVideoInfoPlugin.onMethodCall(FlutterVideoInfoPlugin.java:49)
W/System.err(21861): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
W/System.err(21861): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(21861): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/System.err(21861): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(21861): 	at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err(21861): 	at android.os.Looper.loop(Looper.java:135)
W/System.err(21861): 	at android.app.ActivityThread.main(ActivityThread.java:7325)
W/System.err(21861): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21861): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
W/System.err(21861): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by anandnet** [comment]
Fixed in v 1.1.0. I am closing this for now.
